theme = "fleet_dark"

[editor]
bufferline = "multiple"

[editor.inline-diagnostics]
cursor-line = "hint"

[editor.statusline]
right = ["diagnostics", "selections", "register", "position", "file-encoding", "file-line-ending", "file-indent-style"]
